config/routes.rb
Mybank::Application.routes.draw do

  resources :managers
  resources :customers
  root 'customers#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :managers
end

app/models/manager.rb
class Manager < ApplicationRecord
  belongs_to :customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customer_controller.rb
class CustomerController < ApplicationController
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Cliente criado com sucesso.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        puts " saida = #{customer_params.inspect}"
        format.html { redirect_to @customer, notice: 'Cliente atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Cliente excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :email, :id_manager, :description)
    end
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  def index
  end
end

app/controllers/manager_controller.rb
class ManagerController < ApplicationController
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  before_action :set_manager, only: [:show, :edit, :update, :destroy]

  # GET /managers
  # GET /managers.json
  def index
    @managers = Manager.all
  end

  # GET /managers/1
  # GET /managers/1.json
  def show
  end

  # GET /managers/new
  def new
    @manager = Manager.new
  end

  # GET /managers/1/edit
  def edit
  end

  # POST /managers
  # POST /managers.json
  def create
    @manager = Manager.new(manager_params)

    respond_to do |format|
      if @manager.save
        format.html { redirect_to @manager, notice: 'Gerente criado com sucesso.' }
        format.json { render :show, status: :created, location: @manager }
      else
        format.html { render :new }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /managers/1
  # PATCH/PUT /managers/1.json
  def update
    respond_to do |format|
      if @manager.update(manager_params)
        format.html { redirect_to @manager, notice: 'Gerente atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @manager }
      else
        format.html { render :edit }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /managers/1
  # DELETE /managers/1.json
  def destroy
    @manager.destroy
    respond_to do |format|
      format.html { redirect_to managers_url, notice: 'Gerente excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manager
      @manager = Manager.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manager_params
      params.require(:manager).permit(:name, :email, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/manager_helper.rb
module ManagerHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> Cliente Salvo</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nome %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :Gerente %>
    <p><%=form.collection_select(:id_manager, Manager.all , :id, :name, {:prompt => 'Selecione o gerente.'}) %></p>

  </div>

  <div class="field">
    <%= form.label :Descrição %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit   %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editar Cliente</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Visualizar', @customer %> |
<%= link_to 'Voltar', customers_path %>

app/views/customers/index.html.erb
<% if !flash[:notice].blank? %>
  <div class = "alert alert-info">
    <%= flash[:notice] %>
  </div>
<% end %>

<br />


<h1>Clientes</h1>

<table  class = "table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Nome Gerente</th>
      <th>Descrição</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.email %></td>
        <td><%= Manager.find(customer.id_manager).name %></td>
        <td><%= customer.description %></td>
        <td><%= link_to 'Visualizar', customer   %></td>
        <td><%= link_to 'Editar', edit_customer_path(customer) %></td>
        <td><%= link_to 'Excluir', customer, method: :delete,   data: { confirm: 'Voce têm certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Cliente', new_customer_path %>

app/views/customers/new.html.erb
<h1>Novo Cliente</h1>

<%= render 'form', customer: @customer, :default => "Criar Cliente" %>

<%= link_to 'Voltar', customers_path %>

app/views/customers/show.html.erb
<% if !flash[:notice].blank? %>
  <div class = "alert alert-info">
    <%= flash[:notice] %>
  </div>
<% end %>

<p>
  <strong>Nome:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<p>
  <strong>Nome gerente:</strong>
  <%= Manager.find(@customer.id_manager).name %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @customer.description %>
</p>

<%= link_to 'Editar', edit_customer_path(@customer) %> |
<%= link_to 'Voltar', customers_path %>

app/views/inicio/index.html.erb
<h1>Inicio#index</h1>
<p>Find me in app/views/inicio/index.html.erb</p>

app/views/layouts/application.html.erb
<!--<!DOCTYPE html>-->
<!--<html>-->
<!--<head>-->
<!--  <title>Mybank</title>-->
  <%#= csrf_meta_tags %>
  <%#= csp_meta_tag %>

  <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<!--</head>-->

<!--<body>-->
<%#= yield %>
<!--</body>-->
<!--</html>-->

<!DOCTYPE html>
<html>

<head>
  <title>Mybank</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<table>
  <tr>
    <td><div class="container"><%= link_to 'Gerentes', managers_path %> </div></td>
    <td><div class="container"> <%= link_to 'Clientes', customers_path %></div></td>
  </tr>
</table>


<div class = "container" style = "padding-top:20px;">
  <%= yield %>
</div>
</body>

app/views/managers/_form.html.erb
<%= form_with(model: manager, local: true) do |form| %>
  <% if manager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(manager.errors.count, "error") %> prohibited this manager from being saved:</h2>

      <ul>
      <% manager.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :Descrição %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/managers/edit.html.erb
<h1>Editar Gerente</h1>

<%= render 'form', manager: @manager %>

<%= link_to 'Visualizar', @manager %> |
<%= link_to 'Voltar', managers_path %>

app/views/managers/index.html.erb
<% if !flash[:notice].blank? %>
  <div class = "alert alert-info">
    <%= flash[:notice] %>
  </div>
<% end %>

<br />



<h1>Gerentes</h1>

<table class = "table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Descrição</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @managers.each do |manager| %>
      <tr>
        <td><%= manager.name %></td>
        <td><%= manager.email %></td>
        <td><%= manager.description %></td>
        <td><%= link_to 'Visualizar', manager %></td>
        <td><%= link_to 'Editar', edit_manager_path(manager) %></td>
        <td><%= link_to 'Excluir', manager, method: :delete, data: { confirm: 'Você têm certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Gerente', new_manager_path %>

app/views/managers/new.html.erb
<h1>Novo Gerente</h1>

<%= render 'form', manager: @manager %>

<%= link_to 'Voltar', managers_path %>

app/views/managers/show.html.erb
<% if !flash[:notice].blank? %>
  <div class = "alert alert-info">
    <%= flash[:notice] %>
  </div>
<% end %>

<p>
  <strong>Nome:</strong>
  <%= @manager.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @manager.email %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @manager.description %>
</p>

<%= link_to 'Editar', edit_manager_path(@manager) %> |
<%= link_to 'Voltar', managers_path %>